language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
- PLATFORMIO_CI_SRC=MW_OSD/
install:
- pip install -U platformio
script:
- platformio run
- cd ./
- mkdir dist
- find . -name "*.hex"
- ls -l .pioenvs/
- ls -l .pioenvs/ | grep ^d | tr -s ' ' | cut -d ' ' -f 9 >> filenames.txt;
- while read envname; do echo $envname; cp .pioenvs/$envname/firmware.hex ./dist/$envname.hex; done < filenames.txt;
- ls -l dist/

deploy:
  provider: releases
  api_key:  
    secure: RKtNtyp5uzRhqgjPZLByA5/YWvTs6u01it/L6Oq/jRraiwMdadVH1+4SIXIXv65xWIG12/Tk8ZnxDB3olLk/VA7PS6Cr2UVMgq4wVgU3YL4E9jiMVSvPJ3V6X+BAT2sgDgjuVSx1lkvGPuzzUs0RYxzE5o+/eM+HqdZ56Q3dbSPCzSfxBktjbZYO3gzOhWQ8GgxC8UZ8Pk23IM4YwwLHmDgGjwE+uq05nzgLVn7xXb9VliR1WcRutp6UIU0ZhQ7dCeVoQzUN1jY4gkuJYdZNkiX7U6+ROxib24A7U+miYStq4NUox9C7pctc6LTEH0ON5vr70XbN09VNzpme8B4Z+oTFXLaMvaqePjDryOzTIo99UCbE22eO6xwiZtdi0sQQvXYyEdpSZ/X6mHfYyzOUGV7sn+sRDrJFGXpceU4X5VftEzp60ilBFMItoyoYJWT2O8ENgDh9IDFUr/z3KnfYxppM94nHiV2694Keh81qsb+OWmgAheuHz7tHrsvBBwIKMd45B+5YwZuxDjKUVooKGAgpEfL6piwqjlb2pLN4l/nmT5kCe7jAG8HA7zll2er1i65du31xU8tVON+sEarjn1OU+oIPjWmSNTMacwwbxwHPmYMgxHEn9ImSBpPw63CM97fvW7ZubprH5SmuZ9TFrGQZq3Ljirc19pmZgaXPywU=
  file_glob: true
  file: ./dist/*.hex
  skip_cleanup: true
  overwrite: true
  on:
    repo: ShikOfTheRa/scarab-osd
#   branch: master
    tags: true


## How to generate deploy section
# install git
# install gem
# sudo gem install travis
# cd into repo
# $ travis setup releases --force
# follow prompts..
